[mypy]
python_version = 3.11
ignore_missing_imports = True
warn_unused_ignores = True
no_namespace_packages = True

# (опционально) плагин для pydantic — помогает с типами моделей
plugins = pydantic.mypy
